services:
  api:
    build: .
    env_file: .env
    entrypoint: ["python", "src/init_db.py"]
    command: ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1", "--log-level", "info"]
    environment:
      - TZ=Asia/Tehran
    ports:
      - "8000:8000"
    networks:
      - wework_network
    volumes:
      - ./:/app:rw
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

  frontend:
    image: node:25-alpine
    working_dir: /app
    environment:
      - TZ=Asia/Tehran
      - VITE_API_BASE_URL=/api
      - VITE_PROXY_TARGET=http://api:8000
    ports:
      - "3000:3000"
    networks:
      - wework_network
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped
    # depends_on:
    #   api:
    #     condition: service_healthy

networks:
  wework_network:
    name: wework_network
    external: true